# -*- coding: utf-8 -*-
"""(2020/07/16)Coding365_Flow_Control.ipynb 的副本

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JzNSjmY19yNM--UOD1WvUqLv8JSExmSO

##**Python Commenting Basics**
"""

# This is a single comment. Welcome to Coding365!!!!

'''
This is a multi-line comment
Welcome to Coding365!!!
'''

print('Welcome to Coding365!!!')

"""#**The if Statement**"""

number = 10
if number > 20:
  print("the number is greater than 20")
print("END!")

number = 21
if number > 20:
  print("the number is greater than 20")
print("END!")

number = 10
if number > 20:
  print("the number is greater than 20")
else:
  print("the number is less than 20")
print("END!")

input_score = input('please input your score: ')
input_score = float(input_score)
if input_score >= 90:
  print("Nice!")
elif input_score >= 60:
  print("Pass!")
else:
  print("Failed!!!")

input_score = input('please input your score: ')
input_score = float(input_score)
if input_score >= 90:
  print("Perfect")
elif input_score >= 80:
  print("Excellent")
elif input_score >= 70:
  print("Nice")
elif input_score >= 60:
  print("Pass!")
else:
  print("Failed!!!")

input_gender = input('please input your gender(f or m): ')

if input_gender == 'f' or input_gender == 'm':

  input_age = input('please input your age: ')
  is_int = input_age.isdigit()
  
  if is_int:
    input_age = int(input_age)

    if input_gender == 'f' and input_age < 30 :
      print("Hey! Young lady!")
    elif input_gender == 'm' and not input_age >= 30 :
      print("Hey! Young man!")
    else :
      print("Hey! Old people!")

  else:
    print("OH! Please input correct age!")

else :
  print("OH! Please input f(female) or m(male), thx!")

"""#**The while Statement**"""

timer = 5
while timer > 0: 
  print(timer)
  timer = timer - 1
else:
  print("Boom!")

"""##**Use break command**"""

while True:
  input_string = input("String to capitalize [type q to quit]:")
  if input_string == "q":
      print("quit the program !")
      break
  print(input_string.capitalize())  #capitalize method: change the letter into captical letter

"""##**Use continue command**"""

while True:
  value = input("Integer, please [type q to quit]:")  #wait to type the number
  if value == "q":  # quit
    print("quit the program !")
    break
  number = int(value)
  if number % 2 == 0: # an even number 
    continue
  print(number, "squared is", number*number)

i = 0
while i < 5:
  i = i +1
  if i == 3:
    break
  print(i)

"""#**The for Statement**"""

# for loop example 
for count in range(5, 0, -1):
  print(count)
else:
  print("Boom!")

for i in range(3):
  input_string = input("String to capitalize [type q to quit]:")
  if input_string == "q":
      print("quit the program !")
      break
  print(input_string.capitalize())  #capitalize method: change the letter into captical letter

for i in range(3):
  value = input("Integer, please [type q to quit]:")  #wait to type the number
  if value == "q":  # quit
    print("quit the program !")
    break
  number = int(value)
  if number % 2 == 0: # an even number 
    continue
  print(number, "squared is", number*number)

"""#**Practice**"""

# triangle shape
for i in range(1, 10):
  print("*"*i)

# triangle shape
for i in range(1, 10):
  print(" "*(10-i) + "*"*i)

space = 9
for i in range(1, 18, 2):
  print(" "*space + i*"*")
  space = space -1

for i in range(1, 10):
  print(" "*(10 - i) + "*"*i + "*"*(i-1))

"""## if you finish all practices, try to print the shape of Christmas tree."""

for i in range(2, 5):
  for j in range(1, i*2):
      print(" "*(5*2-1-j)+"*"*(j*2-1))

"""## if you finish all practices, try to print the shape of Diamond."""

for i in range(1, 11):
  print(" "*(11-1-i)+"*"*(i*2-1))
for i in range(1, 10):
  print(" "*i+"*"*((10-i)*2-1))

"""## if you finish all practices, try to design the program that the user input a number n, then design the multiplication table of n*n"""

number = int(input("please input a number: ")) 
for i in range(1, number+1):
  for j in range(0, number+1):
    print(i,"*",j," = ",i*j)